services:
  - type: web
    name: our-home-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
